css/.stickler.yml, ruby/.rubocop.yml
**remove the csslint**  
Many new properties in CSS3 are not recognized in CSSLint and many cases approved by W3 validator are not tolerated in this linter, it will overwhelm students who will waste a lot of time trying to solve every error before realizing they shouldn't use this linter in the first place
**Create .rubocop.yml** 
This will allow students to have more room in the functions and line length, the first is necessary most of the time and the later becomes very handy while trying to test your functions on big arrays.
=> Two changes on the css and ruby configs

ruby/.rubocop.yml
- :describe method in RSpec usually need blocks longer than 25 lines to describe the behavior of a whole class with its methods and contexts and examples.
- Excluding :describe specifically doesn't encourage any bad practices.
- The alternative is to divide the class into multiple :describe methods, which is not ideal.
Theoretically, :context can also need longer blocks in rails applications, but I suggest changes when I discover the need to, hence the incremental spamming of this repository :)
=> Excluded method :describe from the BlockLength

css/README.md
./css/README.md refers to rubocop when it is talking about stylelint.
This pull request replaces the word 'rubocop' with 'stylelint' as it is
referring to the later.
Also a link to stylelint docs can be helpful, so the link is added.
=> Replace the word rubocob with stylelint

README.md
Hi @nidalaa 
For javascript stickler instruction by mistakenly there was `./ruby`. Now it fixed.
=> Javascript link fixed

ruby/.rubocop.yml
I noticed that rubocop wasn't properly excluding the files in `db/` and `config/` directories.
I check the [docs](https://rubocop.readthedocs.io/en/stable/configuration/#includingexcluding-files) and found the correct format to be `root_dir/**/*`
=> updates dir exclusion matcher

javascript/README.md
The [README.md](https://github.com/microverseinc/linters-config/blob/master/javascript/README.md) for the JavaScript configuration says `rubocop` when it means `eslint` 😄 .
=> Fix typo on the README.md for the JavaScript config

javascript/.stickler.yml
Given that webpack would always generate the final JavaScript file in one line with many other efforts to make the final js file light-weight; it makes the final build fail a lot, if not, all ESLint rules.
So, I thought it best we exclude it for stickler. This way, the students won't have a need to tinker with the configuration.
CC: @nidalaa
**Ebuka Umeokonkwo**
[Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)
=> add rule to ignore dist directory for stickler

ruby/.rubocop.yml
I have removed the layout cop for the following reasons:
The following layout cop has been renamed to `Layout/HashAlignment` which is causing warnings when running Rubocop.
```yaml
Layout/AlignHash:
EnforcedColonStyle: key
```
See Rubocop docs on [Layout/HashAlignment](https://docs.rubocop.org/en/latest/cops_layout/#layouthashalignment)
This cop can now be removed altogether as the default Rubocop setting for `Layout/HashAlignment` is now `EnforcedColonStyle: key`.
=> Remove legacy layout cop from rubocop config file

javascript/eslint.config
I created two PR to test this config file. One with the old config: https://github.com/bolah2009/js-testing-parserOptions/pull/1 and other with the new config: https://github.com/bolah2009/js-testing-parserOptions/pull/2
@nidalaa
=> Change parser ecma version to 2018

README.md, Ruby_less_restrictive/.rubocop.yml, ror/.rubocop.yml, ror/.stickler.yml, ror/README.md, ruby/.rubocop.yml, ruby/README.md
- created a `ror/` folder and copied `.rubocop.yml` config file i worked on few days ago which was a little less restrictive(or more friendly)
- also copied STICKLER from `ruby/` folder into `ror/` folder
- removed from `ruby/.rubocop.yml` file configs specific to RAILS projects
- crosschecked `ror/.rubocop.yml` file if there should be anything specific to ruby alone (it was OK)
- edited general README, to include links to Ruby & Rails folders
- edited heading of Ruby & Rails READMEs to have specific course-title
=> separating Ruby and ROR rubocop configs

javascript/eslint.config
As a follow-up to this PR #31 this PR fixes the second issue raised in the previous PR:
> * [ ] Browser specific methods may not work correctly with the current config with not `env` values defined. An example below is stickler not recognising the [Web Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
This PR adds `env` property and it's respective value so that browser, es6 and jest specific methods/features will be recognized.
``` json
"env": {
"browser": true,
"es6": true,
"jest": true
}
```
Like in the react/redux config, the first property will support `browser`, `ES6` and  `jest` global variables.
More details here: https://eslint.org/docs/user-guide/configuring#specifying-environments
=> Specify environments for predefined global variables

README.md
The link to the JavaScript troubleshooting section on the main README is pointing to the Ruby section.
=> Fix typo on link

ruby/.rubocop.yml
updated the name from Metrics/LineLength to Layout/LineLength
Please, I would really appreciate it if my pull request is merged. I'm so excited to find this out.
=> Wrong Namespace: Rubocop

ror/.rubocop.yml
Rubocop namespace as introduced here this change was introduced here https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#changes-2.
`Metrics/LineLength` is `Layout/LineLength` now.
=> Change obsolete Rubocop namespace for Linelength cop

ror/.rubocop.yml, ror/README.md, ruby/.rubocop.yml, ruby/README.md
Fix for address the issue #43 
```
Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
```
=> Fixing Rubocop error

javascript/.eslintrc.json, react-redux/.eslintrc.json, react-redux/README.md
- They consist of the following, the error that was brought to us was that the stickler check was bringing an error related to the arrow-parens rule which states, according to the documentation, that even if there is only one parameter being passed in an arrow function it does require for it to be enclosed in parens. But the stickler check thinks otherwise, and since there is no way to bypass this error, the only solution would be to turn off the arrow-parens rule in the local environment so that we can have a consistent linting in all stages of development.
- The change proposed for the react section follows along with the same principles. And there is also a change in the README file to be more consistent with the Javascript section one.
=> Changes to the rules to be consistent with stickler errors.

javascript/README.md
- The issue is the following: 
- The Library Project and the Tic Tac Toe project, explore concepts in the spectrum of programing paradigms, factory functions, module pattern, objects, and constructors, in these projects we are not using webpack yet, which means the active use of node package modules is not yet introduced. I've made a couple of reviews for those projects where the `package.json` file was not present at all, meaning that running `npx eslint --init` and `npx eslint .` will not provide the proper functionality for linting in the IDE, neither will it make stickler behavior predictable.
So I added a couple of lines to fix this:
This will avoid confusion from newcomers to the Javascript section.
=> Added extra line on the README for the JS linter config

react-redux/.eslintrc.json
By setting **"arrow-paren"s** to **"Off"** some **"ugly"** code can skip through a developer's eye.
**Airbnb** standard [here](https://github.com/airbnb/javascript#arrow-functions) thinks it's a good idea to set **"arrow-parens"** to **"always"**, to enforce the use of parenthesis around argument (single or multiple).
On the other hand, **Eslint** [here](https://eslint.org/docs/rules/arrow-parens#further-reading) was inspired by **Airbnb** to add support for **"arrow-parens"** set to **"as-needed"**. This update will also enable code formatters like **Prettier** to automagically include parenthesis on multiple arguments, and remove them from single arguments.
In this PR, I suggest, to set **"arrow-parens"** to **"as-needed"**, rather than **"Off"** to enforce style, encourage the …
=> Turn "on" arrow-parens rule to enforce style

README.md, scripts/README.md, scripts/check-linters-conf.sh
`check-linters-config` is a bash script to compare local files against the files on the master branch of this repository. It will Check that files exist and that they are identical to the ones here.
1. Copy the [`check-linters-conf.sh`](check-linters-conf.sh) file into someplace in the `$PATH` of your machine, for example `/usr/local/bin`:
```sh
sudo wget -O /usr/local/bin/check-linters-config https://raw.githubusercontent.com/MauricioRobayo/linters-config/feature/verification-script/scripts/check-linters-conf.sh
```
2. Make it executable:
```
sudo chmod +x /usr/local/bin/check-linters-config
```
Run the command `check-linters-config` on the root of the repository you want to check. It takes as an argument the name of the directory you want to check against.
```sh
$ check-linters-config …
```
=> Bash script to compare linters files

css/.stickler.yml
It would be nice if we avoid situations where students have to modify the stickler configuration file just to ignore the reset file they got from somewhere on the Internet, and as an added benefit, they'll be forced to have a `css/` folder where they should place all of their stylesheets.
=> add `reset.css` to ignored files

javascript/README.md
- Replaced the part that involves using `npx eslint --init`, with all the question answers part.
- Placed instead one single command that installs all the required dependencies and `eslint` itself.
- Modified the item that gives instructions for replacing the generated `.eslintrc.json` file.
If you disagree with these changes please let me know.
=> simplify eslint installation instructions

ror/README.md
- Added a troubleshoot section.
- Added instructions to remove the Stylelint config from the [linter.yml](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml) file
=> Updated ror Readme with the info to resolve the stylelint error for API only Rails app(#83)

javascript/.eslintrc.json, javascript/.github/workflows/linters.yml, react-redux/.eslintrc.json, react-redux/.github/workflows/linters.yml
This PR solves the issue of Eslint not recognising some JS features. `babel-eslint` is added as the parser to solve this issue. 
See https://github.com/bolah2009/js-testing-parserOptions/pull/5 for example of how `babel-eslint` handled the use of arrow function in js class.
See https://github.com/bolah2009/js-testing-parserOptions/pull/6 for example of how eslint fails to parse the syntax
=> Add babel eslint for parsing non-standard js features

README.md, html-css/README.md, javascript/README.md, react-redux/README.md, ror/README.md, ruby/README.md
The intent of the pull request is to remove the reference to the former linter configuration(stickler) as it is almost 2 months since the switch and I still see students using it, the reference on there makes it look like stickler is an option, so I believe removing it now is the best way to emphasis that it isn't and everyone should use GitHub actions.
=> remove reference to stickler

scripts/README.md
Added specific instructions to compare with the original file if terminal renders differ with proper examples.
=> Added instructions for comparing linter config

react-redux/.eslintrc.json
react/react-in-jsx-scope should be disabled since react doesn't need 
```javascript
import React from 'react'
```
anymore in components made with functions.
I think it's better to let the student decide to add it or not, and in places where it's supposed to be added (component classes) React wouldn't work without it so they'll need to add it anyway, so I think this rule is useless.
=> Disabled react/react-in-jsx-scope

react-redux/.github/workflows/linters.yml, react-redux/README.md
Changed ESLint package version from `6.8.x` to `7.11.x`
since `npx create-react-app` always try to use the latest version (recommended as well), today while I was working on my project I received this error when I applied the linters
it was due to the `ESLint` package version being outdated, so we should update the version here so students wouldn't get this error
Fixes #108
=> Update ESlint version

ruby/.github/workflows/tests.yml
This PR removes the deprecated --deployment flag from ruby and rails related config:
- This will help suppress the deprecation warnings from bundler, more [here](https://github.com/rubygems/bundler/blob/d4993be66fa2e76b3ca00ea56a51ecab5478b726/UPGRADING.md#bundler-3)
- This would not prevent errors when the user does not commit `Gemfile.lock` file
```
The --deployment flag requires a Gemfile.lock. Please make sure you have checked 
your Gemfile.lock into version control before deploying.
```
=> Remove --deployment flag from ruby related config

ruby/.github/workflows/linters.yml, ruby/.rubocop.yml
This change at the linters.yml for ruby projects fix the linters not working on ruby 3.0.X.
It works on any ruby version equal or higher than Ruby 2.6.X
=> Update linters yml for ruby with latest rubocop

ruby/.rubocop.yml
I added a line to exclude the node_modules folder since it's been messing with it to some students.
more [here](https://microverse-students.slack.com/archives/GA812K2TC/p1615310273054200)
=> Exclude node_modules folder

html-css/.hintrc
I've added the `inline-style-disabled` hint so students will no longer use stylings on the HTML
Fixes #120
=> Add "inline-style-disabled" Hint

javascript/.eslintrc.json, react-redux/.eslintrc.json
Removed [`arrow-parens`](https://eslint.org/docs/rules/arrow-parens) rule from React-Redux configuration
on JavaScript, it's set to off, but since it's off by default (tested), I removed the line as well.
Fixes #135
=> Remove arrow-parens rule

html-css/.github/workflows/linters.yml, html-css/README.md, javascript/.github/workflows/linters.yml, javascript/README.md, react-redux/.github/workflows/linters.yml, react-redux/README.md, ror/.github/workflows/linters.yml, ror/.rubocop.yml, ror/README.md, ruby/.github/workflows/linters.yml, ruby/.github/workflows/tests.yml, ruby/README.md
We've had to update ESLint for React so it works with the latest version of it (see #109), but there are 2 packages that should've also been updated to work with the new ESLint version. for some reason, they worked fine on `npm@6`, but not on `npm@7`.
Updated `eslint-plugin-react-hooks@2.5.x` to `eslint-plugin-react-hooks@4.1.x` [[see changelog](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/CHANGELOG.md)]
Updated `eslint-config-airbnb@18.1.x` to `eslint-config-airbnb@18.2.x` [[see changelog](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md)]
I've also **updated all packages** to their latest version so they work with new Node or Ruby versions.
tested and everything should work fine.
Fixes #141
=> Bump up outdated packages

react-redux/.stylelintrc.json
this PR adds .js and .jsx files to the ignore list of Stylelint configurations on the React project, this normally wouldn't be an issue, but if you're using an extension to check stylelint errors, it might give false-positive errors.
learn more on #145 
Fixes #145
=> Ignore JS and JSX files on Stylelint

ror/.stylelintrc.json
Update `scss/at-rule-no-unknown` rule to accept tailwind directives.
PR examples
with old config : https://github.com/od-c0d3r/tailwind-rails/runs/5581436235?check_suite_focus=true
win new config : https://github.com/od-c0d3r/tailwind-rails/runs/5581642045?check_suite_focus=true
**Note:** to test 
1. Follow tailwind [instructions](https://tailwindcss.com/docs/guides/ruby-on-rails) to create a rails project
2. There is an [issue](https://youtrack.jetbrains.com/issue/RUBY-29159) with tailwind build in Rails 7 so after using tailwind classes make sure to run `rails tailwindcss:build` to package your styles
=> Update `./ror/stylelintrc.json` for tailwind 

html-css-js/.github/workflows/linters.yml, html-css/.github/workflows/linters.yml, react-redux/.github/workflows/linters.yml, ror/.github/workflows/linters.yml
In this PR I:
- Created a GitHub action job that checks the existence of a `node_modules` folder on the PR.
- If the folder exists, it fails and exits with exit code 1.
- If the folder does not exist, it passes the check.
- For the students, I added the reason for the error in red color and the possible solution (.gitignore) in green.
This is a possible solution for the problem that occurs when a student forgets to set up a `.gitignore` file, and inadvertently pushes the `node_modules` folder to the repo.  
Since the `node_modules` folder pushes more than 5000 files to the PR, this was causing some of the CR computers to slow to a crawl, preventing them to write proper, explanatory invalidation messages.
With this GitHub workflow, students will be reminded to not push the `node_modules` …
=> add nodechecker for all remaining modules except Ruby

html-css-js/.github/workflows/linters.yml, html-css-js/README.md, html-css/.github/workflows/linters.yml, html-css/README.md
We are currently using version 6 of webhint and some dependencies cannot be met for this version.  ([Case 1](https://github.com/Abdullah2213565/Portfolio-Project-1/pull/10)) ([Case 2](https://github.com/sharon-odhiambo/My-Portfolio-Site/pull/8)) ([Case 3](https://github.com/Pamphilemkp/My_professional_portfolio/pull/11))
The 7th version of webhint doesn’t have the same issue.
This PR updates webhint version to 7 to prevent this issues
=> Update webhint to version 7

html-css-js/README.md
@nidalaa, 
This link [auto-correct options for Stylelint](https://stylelint.io/user-guide/cli#autofixing-errors) seems not working anymore, I replace it with a helpful link.
Fix a typo and added Eslint auto-fix documentation link.
If you're ok with the PR, kindly approve. I will update the rest of the files that need correction.
=> Replace broken link.

react-redux/.github/workflows/linters.yml, react-redux/README.md
Our current linter config for React-Redux doesn't catch any error in `jsx` file. [PR](https://github.com/Htetaungkyaw71/BookStore-React/pull/3) example
For some reason, `jsx` file extension is ignored.
I update these files to specify `jsx` and also update the README file for students to be able to run the command locally.
=> Specify jsx and js check

html-css-js/.github/workflows/linters.yml, html-css/.github/workflows/linters.yml, javascript/.github/workflows/linters.yml, react-redux/.github/workflows/linters.yml, ror/.github/workflows/linters.yml, ruby/.rubocop.yml
Linter: node would be deprecated next year summer, we start to get warnings for now.
[GitHub documentation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
@nidalaa @NoerGitKat
=> Update to Node version 18 for linters config

html-css-js/.github/workflows/linters.yml, html-css/.github/workflows/linters.yml
There have been some linting errors for students in module 1 (html-css) and module 2 (html-css-js). This PR updates the GH actions for `checkout` and `setup-node` to support the use of Node.js v18.
=> Updated html-css and html-css-js linter config

ror/.rubocop.yml
When you run rubocop it sets out a warning: 
"obsolete parameter `IgnoredMethods` (for `Metrics/BlockLength`) found in .rubocop.yml `IgnoredMethods` has been renamed to `AllowedMethods` and/or `AllowedPatterns`."
This fix removes the warning and allows the user to concentrate on the report.
=> Update rubocop yml for obsolete methods
